os:
  - linux

language: c

before_script:
  - git clone https://github.com/awslabs/git-secrets.git
  - pushd git-secrets
  - sudo make install
  - popd
  - git secrets --install
  - git secrets --register-aws

script:
  - git secrets --scan  
